#!/usr/bin/env python3
"""
BrandSentra - Shared Detection Knowledge

Keyword lists, TLD risk tiers and token sets used by the phishing detector,
the squatting analyzer and the brand monitor. Keeping them in one place
means a new lure word or abused TLD only has to be added once.
"""

from __future__ import annotations

from typing import Dict, FrozenSet, Set

#: Generic phishing lure words seen in registrable labels and subdomains.
PHISHING_KEYWORDS: FrozenSet[str] = frozenset(
    {
        "login",
        "log-in",
        "signin",
        "sign-in",
        "logon",
        "verify",
        "verification",
        "verified",
        "secure",
        "security",
        "update",
        "updates",
        "confirm",
        "confirmation",
        "account",
        "accounts",
        "suspend",
        "suspended",
        "restrict",
        "restricted",
        "unlock",
        "recover",
        "recovery",
        "validate",
        "validation",
        "authenticate",
        "authentication",
        "auth",
        "bank",
        "banking",
        "ebanking",
        "netbanking",
        "onlinebanking",
        "payment",
        "payments",
        "wallet",
        "credential",
        "credentials",
        "password",
        "passcode",
        "otp",
        "pin",
        "kyc",
        "ssn",
        "social-security",
        "tax-refund",
        "refund",
        "invoice",
        "billing",
        "statement",
        "alert",
        "notice",
        "urgent",
        "activate",
        "activation",
        "renew",
        "renewal",
        "reward",
        "rewards",
        "bonus",
        "gift",
        "giftcard",
        "prize",
        "winner",
        "promo",
        "cashback",
        "fine",
        "fines",
        "traffic",
        "violation",
        "delivery",
        "parcel",
        "shipment",
        "customs",
        "helpdesk",
        "support",
        "webmail",
        "mailbox",
        "docusign",
        "sharepoint",
        "onedrive",
        "office365",
        "office-365",
        "microsoft365",
    }
)

#: Words that turn a brand name into a "combo-squat" (``nbk-login.com``).
COMBO_KEYWORDS: FrozenSet[str] = frozenset(
    {
        "login",
        "signin",
        "logon",
        "secure",
        "security",
        "verify",
        "verification",
        "update",
        "account",
        "accounts",
        "support",
        "service",
        "services",
        "online",
        "portal",
        "auth",
        "bank",
        "banking",
        "pay",
        "payment",
        "payments",
        "wallet",
        "mobile",
        "app",
        "apps",
        "web",
        "mail",
        "email",
        "cloud",
        "admin",
        "reset",
        "confirm",
        "validation",
        "validate",
        "otp",
        "card",
        "cards",
        "kyc",
        "help",
        "helpdesk",
        "alert",
        "alerts",
        "notice",
        "activate",
        "activation",
        "renew",
        "renewal",
        "refund",
        "reward",
        "rewards",
        "bonus",
        "gift",
        "prize",
        "promo",
        "offer",
        "offers",
        "cashback",
        "invoice",
        "billing",
        "statement",
        "ebank",
        "ebanking",
        "netbanking",
        "official",
        "my",
        "new",
        "the",
        "go",
        "get",
        "click",
        "link",
        "info",
        "id",
        "fine",
        "fines",
        "traffic",
        "visa",
        "tax",
        "loan",
        "loans",
        "credit",
        "transfer",
        "customer",
        "customers",
        "client",
        "user",
        "users",
        "team",
        "center",
        "centre",
        "group",
        "global",
        "international",
        "digital",
        "smart",
        "express",
        "direct",
        "plus",
        "pro",
        "live",
        "now",
        "gov",
        "me",
        "com",
        "net",
        "org",
        "www",
        "booking",
        "book",
        "flight",
        "flights",
        "ticket",
        "tickets",
        "checkin",
        "reservation",
        "shop",
        "store",
        "order",
        "orders",
        "track",
        "tracking",
        "delivery",
        "parcel",
        "topup",
        "recharge",
        "balance",
        "bill",
        "bills",
        "sim",
        "esim",
        "data",
        "internet",
        "fiber",
        "wifi",
        "5g",
        "points",
        "miles",
        "loyalty",
        "salary",
        "deposit",
        "savings",
        "investment",
        "trading",
        "stocks",
        "crypto",
        "job",
        "jobs",
        "career",
        "careers",
        "hr",
    }
)

#: Tokens that signal enterprise, financial, or authentication context around a short brand name.
CONTEXT_TOKENS: FrozenSet[str] = frozenset(
    {"bank", "gov", "online", "pay", "secure", "portal", "corp", "verify", "account", "login", "cloud", "auth"}
)

#: Global brands frequently impersonated in credential phishing.
GLOBAL_BRANDS: FrozenSet[str] = frozenset(
    {
        "microsoft",
        "office365",
        "outlook",
        "onedrive",
        "sharepoint",
        "apple",
        "icloud",
        "google",
        "gmail",
        "amazon",
        "paypal",
        "netflix",
        "facebook",
        "instagram",
        "whatsapp",
        "telegram",
        "linkedin",
        "dropbox",
        "adobe",
        "docusign",
        "dhl",
        "fedex",
        "aramex",
        "usps",
        "binance",
        "coinbase",
        "metamask",
        "steam",
        "spotify",
        "chase",
        "hsbc",
        "citibank",
        "wellsfargo",
        "americanexpress",
        "mastercard",
    }
)

#: Enterprise brand tokens used by the lightweight detector heuristics.
BRAND_TOKENS: FrozenSet[str] = frozenset(
    {
        "novapay",
        "kestrel",
        "kestrelmart",
        "halcyon",
        "halcyonhealth",
        "meridian",
        "meridianbank",
        "apexcloud",
        "lumina",
        "luminatelecom",
        "vertexsec",
        "vertexsecurity",
        "horizonlogistics",
        "sentra",
        "brandsentra",
    }
)

#: Arabic-script lure words (normalised with ``normalize_arabic``).
ARABIC_PHISHING_KEYWORDS: Dict[str, str] = {
    "تحديث": "update",
    "تفعيل": "activate",
    "تاكيد": "confirm",
    "حساب": "account",
    "بطاقه": "card",
    "دخول": "login",
    "تسجيل": "register",
    "امن": "secure",
    "بنك": "bank",
    "دفع": "pay",
    "جايزه": "prize",
    "هديه": "gift",
    "مكافاه": "reward",
    "غرامه": "fine",
    "مخالفه": "violation",
    "حكومه": "government",
    "توصيل": "delivery",
    "شحنه": "shipment",
    "رمز": "code",
    "كلمه المرور": "password",
    "الهويه": "identity",
    "المدنيه": "civil",
    "تحويل": "transfer",
    "استرداد": "refund",
    "عرض": "offer",
    "مجاني": "free",
    "عاجل": "urgent",
}

#: TLD risk tiers. High risk: free / near-free registries dominated by abuse.
HIGH_RISK_TLDS: FrozenSet[str] = frozenset(
    {
        "tk",
        "ml",
        "ga",
        "cf",
        "gq",
        "buzz",
        "icu",
        "cyou",
        "rest",
        "monster",
        "cam",
        "bar",
        "mom",
        "quest",
        "sbs",
        "cfd",
        "bond",
        "lol",
        "zip",
        "mov",
        "surf",
        "wang",
        "loan",
        "win",
        "bid",
        "stream",
        "download",
        "racing",
        "review",
        "party",
        "trade",
        "date",
        "faith",
        "science",
        "accountant",
        "men",
        "gdn",
        "kim",
        "country",
        "cricket",
    }
)

MEDIUM_RISK_TLDS: FrozenSet[str] = frozenset(
    {
        "xyz",
        "top",
        "club",
        "online",
        "site",
        "work",
        "click",
        "link",
        "info",
        "biz",
        "pw",
        "live",
        "shop",
        "store",
        "vip",
        "fun",
        "space",
        "website",
        "tech",
        "digital",
        "cloud",
        "world",
        "life",
        "today",
        "email",
        "support",
        "help",
        "center",
        "services",
        "solutions",
        "finance",
        "money",
        "cash",
        "bank",
        "credit",
        "pics",
        "run",
        "fit",
        "best",
        "one",
        "asia",
        "cc",
        "ws",
        "su",
        "ru",
        "cn",
        "co",
        "me",
        "app",
        "page",
        "dev",
    }
)

#: Legitimate second-level suffixes for official institutions; used for "official-looking" checks.
OFFICIAL_SUFFIXES: Set[str] = {"gov", "edu", "mil", "int"}

RISK_LEVEL_ORDER: Dict[str, int] = {"critical": 4, "high": 3, "medium": 2, "low": 1, "clean": 0}


def score_to_level(score: float) -> str:
    """Map a 0-100 risk score to a risk level string."""
    if score >= 80:
        return "critical"
    if score >= 60:
        return "high"
    if score >= 40:
        return "medium"
    if score >= 20:
        return "low"
    return "clean"


def bump_level(level: str, steps: int = 1) -> str:
    """Raise a risk level by ``steps`` (capped at critical)."""
    order = ["clean", "low", "medium", "high", "critical"]
    idx = order.index(level) if level in order else 0
    return order[min(len(order) - 1, idx + steps)]


def tld_risk(suffix: str) -> str:
    """Return ``high``, ``medium`` or ``none`` for a public suffix / TLD."""
    if not suffix:
        return "none"
    last = suffix.split(".")[-1].lower()
    if last in HIGH_RISK_TLDS:
        return "high"
    if last in MEDIUM_RISK_TLDS:
        return "medium"
    return "none"


__all__ = [
    "ARABIC_PHISHING_KEYWORDS",
    "BRAND_TOKENS",
    "COMBO_KEYWORDS",
    "CONTEXT_TOKENS",
    "GLOBAL_BRANDS",
    "HIGH_RISK_TLDS",
    "MEDIUM_RISK_TLDS",
    "OFFICIAL_SUFFIXES",
    "PHISHING_KEYWORDS",
    "RISK_LEVEL_ORDER",
    "bump_level",
    "score_to_level",
    "tld_risk",
]
