#!/usr/bin/env python3
"""
Export the detection engine's data tables to ``demo/engine-data.js``.

The browser dashboard ships a JavaScript port of the detection engine so the
GitHub Pages demo performs real analysis without a backend. This script keeps
the brand profiles, keyword lists, TLD tiers, suffix tables and confusable
maps identical to the Python engine; ``tests/test_js_engine.py`` fails when
the generated file is stale.

Usage:
    python scripts/export_engine_data.py            # write demo/engine-data.js
    python scripts/export_engine_data.py --check    # exit 1 when out of date
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from src import __version__  # noqa: E402
from src.config.settings import (  # noqa: E402
    DEFAULT_SQUAT_TLDS,
    CertStreamConfig,
    DomainAnalysisConfig,
)
from src.core import constants  # noqa: E402
from src.core.brand_monitor import DEFAULT_BRANDS  # noqa: E402
from src.core.domain_analyzer import (  # noqa: E402
    GENERATION_COMBOS,
    HOMOGLYPHS,
    KEYBOARD_ADJACENT,
    LEET_GENERATION,
)
from src.core.phishing_detector import (  # noqa: E402
    EMBEDDED_TLD_TOKENS,
    FREE_CA_MARKERS,
    OFFICIAL_TOKENS,
)
from src.utils import domain as dom  # noqa: E402

OUTPUT = ROOT / "demo" / "engine-data.js"


def build_data() -> dict:
    """Assemble every table the JavaScript engine needs."""
    brands = []
    for b in DEFAULT_BRANDS:
        item = b.to_dict()
        item["primary_labels"] = sorted(b.primary_labels())
        item["alias_labels"] = sorted(b.alias_labels())
        item["phrases"] = b.phrases()
        item["arabic_normalized"] = [dom.normalize_arabic(k) for k in b.arabic_keywords]
        brands.append(item)
    return {
        "version": __version__,
        "brands": brands,
        "protected_brands": list(DomainAnalysisConfig().protected_brands),
        "certstream_keywords": list(CertStreamConfig().keywords),
        "squat_tlds": list(DEFAULT_SQUAT_TLDS),
        "phishing_keywords": sorted(constants.PHISHING_KEYWORDS),
        "combo_keywords": sorted(constants.COMBO_KEYWORDS),
        "context_tokens": sorted(constants.CONTEXT_TOKENS),
        "global_brands": sorted(constants.GLOBAL_BRANDS),
        "brand_tokens": sorted(constants.BRAND_TOKENS),
        "arabic_lures": dict(constants.ARABIC_PHISHING_KEYWORDS),
        "high_risk_tlds": sorted(constants.HIGH_RISK_TLDS),
        "medium_risk_tlds": sorted(constants.MEDIUM_RISK_TLDS),
        "official_suffixes": sorted(constants.OFFICIAL_SUFFIXES),
        "official_tokens": sorted(OFFICIAL_TOKENS),
        "embedded_tld_tokens": sorted(EMBEDDED_TLD_TOKENS),
        "free_ca_markers": list(FREE_CA_MARKERS),
        "suffixes": {
            "regional": sorted(dom.REGIONAL_SUFFIXES),
            "gcc_mena": sorted(dom.GCC_MENA_SUFFIXES),
            "global": sorted(dom.GLOBAL_SUFFIXES),
            "free_hosting": sorted(dom.FREE_HOSTING_SUFFIXES),
        },
        "confusables": dict(dom.CONFUSABLES),
        "leet_map": dict(dom.LEET_MAP),
        "visual_sequences": [list(x) for x in dom.VISUAL_SEQUENCES],
        "keyboard_adjacent": dict(KEYBOARD_ADJACENT),
        "homoglyphs": {k: list(v) for k, v in HOMOGLYPHS.items()},
        "leet_generation": {k: list(v) for k, v in LEET_GENERATION.items()},
        "generation_combos": list(GENERATION_COMBOS),
    }


def render() -> str:
    payload = json.dumps(build_data(), ensure_ascii=False, indent=1, sort_keys=True)
    return (
        "// Generated by scripts/export_engine_data.py from the Python engine. Do not edit.\n"
        "/* eslint-disable */\n"
        f"(function(g){{g.KCW_DATA={payload};}})"
        "(typeof window!=='undefined'?window:globalThis);\n"
    )


def main(argv: list) -> int:
    text = render()
    if "--check" in argv:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != text:
            print(f"{OUTPUT.relative_to(ROOT)} is out of date; run scripts/export_engine_data.py")
            return 1
        print("engine data up to date")
        return 0
    OUTPUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)} ({len(text)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
