// Generated by scripts/export_engine_data.py from the Python engine. Do not edit.
/* eslint-disable */
(function(g){g.KCW_DATA={
 "arabic_lures": {
  "استرداد": "refund",
  "المدنيه": "civil",
  "الهويه": "identity",
  "امن": "secure",
  "بطاقه": "card",
  "بنك": "bank",
  "تاكيد": "confirm",
  "تحديث": "update",
  "تحويل": "transfer",
  "تسجيل": "register",
  "تفعيل": "activate",
  "توصيل": "delivery",
  "جايزه": "prize",
  "حساب": "account",
  "حكومه": "government",
  "دخول": "login",
  "دفع": "pay",
  "رمز": "code",
  "شحنه": "shipment",
  "عاجل": "urgent",
  "عرض": "offer",
  "غرامه": "fine",
  "كلمه المرور": "password",
  "مجاني": "free",
  "مخالفه": "violation",
  "مكافاه": "reward",
  "هديه": "gift"
 },
 "brand_tokens": [
  "apexcloud",
  "brandsentra",
  "halcyon",
  "halcyonhealth",
  "horizonlogistics",
  "kestrel",
  "kestrelmart",
  "lumina",
  "luminatelecom",
  "meridian",
  "meridianbank",
  "novapay",
  "sentra",
  "vertexsec",
  "vertexsecurity"
 ],
 "brands": [
  {
   "alias_labels": [
    "novapya"
   ],
   "aliases": [
    "n0vapay",
    "novapya"
   ],
   "arabic_keywords": [
    "نوفاباي"
   ],
   "arabic_normalized": [
    "نوفاباي"
   ],
   "domains": [
    "novapay.com",
    "novapay.net"
   ],
   "industry": "payments",
   "keywords": [
    "novapay",
    "nova pay",
    "novapay support"
   ],
   "name": "NovaPay",
   "phrases": [
    [
     "nova",
     "pay"
    ],
    [
     "novapay",
     "support"
    ]
   ],
   "primary_labels": [
    "novapay"
   ],
   "priority": "critical",
   "short_name": "NovaPay"
  },
  {
   "alias_labels": [
    "kestrel"
   ],
   "aliases": [
    "kestrel"
   ],
   "arabic_keywords": [],
   "arabic_normalized": [],
   "domains": [
    "kestrelmart.com"
   ],
   "industry": "ecommerce",
   "keywords": [
    "kestrelmart",
    "kestrel mart"
   ],
   "name": "Kestrel Mart",
   "phrases": [
    [
     "kestrel",
     "mart"
    ]
   ],
   "primary_labels": [
    "kestrelmart"
   ],
   "priority": "high",
   "short_name": "Kestrel"
  },
  {
   "alias_labels": [
    "halcyon"
   ],
   "aliases": [
    "halcyon"
   ],
   "arabic_keywords": [],
   "arabic_normalized": [],
   "domains": [
    "halcyonhealth.org"
   ],
   "industry": "healthcare",
   "keywords": [
    "halcyonhealth",
    "halcyon health"
   ],
   "name": "Halcyon Health",
   "phrases": [
    [
     "halcyon",
     "health"
    ]
   ],
   "primary_labels": [
    "halcyonhealth"
   ],
   "priority": "high",
   "short_name": "Halcyon"
  },
  {
   "alias_labels": [
    "nbkbank",
    "nbkonline",
    "watani"
   ],
   "aliases": [
    "nbkonline",
    "nbkbank"
   ],
   "arabic_keywords": [
    "الوطني"
   ],
   "arabic_normalized": [
    "الوطني"
   ],
   "domains": [
    "nbk.com",
    "nbkcapital.com"
   ],
   "industry": "banking",
   "keywords": [
    "nbk",
    "national banking corporation",
    "watani"
   ],
   "name": "National Banking Corporation (NBK)",
   "phrases": [
    [
     "national",
     "banking",
     "corporation"
    ]
   ],
   "primary_labels": [
    "nbk",
    "nbkcapital"
   ],
   "priority": "critical",
   "short_name": "NBK"
  },
  {
   "alias_labels": [
    "baitak",
    "kfhbank",
    "kfhonline"
   ],
   "aliases": [
    "kfhonline",
    "kfhbank"
   ],
   "arabic_keywords": [
    "بيتك"
   ],
   "arabic_normalized": [
    "بيتك"
   ],
   "domains": [
    "kfh.com"
   ],
   "industry": "banking",
   "keywords": [
    "kfh",
    "key finance house",
    "key finance",
    "baitak"
   ],
   "name": "Key Finance House (KFH)",
   "phrases": [
    [
     "key",
     "finance",
     "house"
    ],
    [
     "key",
     "finance"
    ]
   ],
   "primary_labels": [
    "kfh"
   ],
   "priority": "critical",
   "short_name": "KFH"
  },
  {
   "alias_labels": [],
   "aliases": [],
   "arabic_keywords": [],
   "arabic_normalized": [],
   "domains": [
    "cbk.com"
   ],
   "industry": "government",
   "keywords": [
    "cbk",
    "central banking authority"
   ],
   "name": "Central Banking Authority (CBK)",
   "phrases": [
    [
     "central",
     "banking",
     "authority"
    ]
   ],
   "primary_labels": [
    "cbk"
   ],
   "priority": "critical",
   "short_name": "CBK"
  },
  {
   "alias_labels": [
    "altijari",
    "tijari"
   ],
   "aliases": [],
   "arabic_keywords": [
    "التجاري"
   ],
   "arabic_normalized": [
    "التجاري"
   ],
   "domains": [
    "cbk.com",
    "cbkonline.com"
   ],
   "industry": "banking",
   "keywords": [
    "commercial banking group",
    "tijari",
    "altijari"
   ],
   "name": "Commercial Banking Group (Al-Tijari)",
   "phrases": [
    [
     "commercial",
     "banking",
     "group"
    ]
   ],
   "primary_labels": [
    "cbk",
    "cbkonline"
   ],
   "priority": "high",
   "short_name": "Al-Tijari"
  },
  {
   "alias_labels": [],
   "aliases": [],
   "arabic_keywords": [
    "برقان"
   ],
   "arabic_normalized": [
    "برقان"
   ],
   "domains": [
    "burgan.com"
   ],
   "industry": "banking",
   "keywords": [
    "burgan",
    "burgan bank"
   ],
   "name": "Burgan Bank",
   "phrases": [
    [
     "burgan",
     "bank"
    ]
   ],
   "primary_labels": [
    "burgan"
   ],
   "priority": "high",
   "short_name": "Burgan"
  },
  {
   "alias_labels": [
    "egulfbank"
   ],
   "aliases": [],
   "arabic_keywords": [
    "بنك الخليج"
   ],
   "arabic_normalized": [
    "بنك الخليج"
   ],
   "domains": [
    "e-gulfbank.com",
    "gulfbank.com"
   ],
   "industry": "banking",
   "keywords": [
    "gulfbank",
    "gulf bank",
    "egulfbank"
   ],
   "name": "Gulf Bank",
   "phrases": [
    [
     "gulf",
     "bank"
    ]
   ],
   "primary_labels": [
    "e-gulfbank",
    "gulfbank"
   ],
   "priority": "high",
   "short_name": "Gulf Bank"
  },
  {
   "alias_labels": [],
   "aliases": [],
   "arabic_keywords": [
    "بوبيان"
   ],
   "arabic_normalized": [
    "بوبيان"
   ],
   "domains": [
    "bankboubyan.com",
    "boubyan.com"
   ],
   "industry": "banking",
   "keywords": [
    "boubyan",
    "boubyan bank",
    "bank boubyan"
   ],
   "name": "Boubyan Bank",
   "phrases": [
    [
     "boubyan",
     "bank"
    ],
    [
     "bank",
     "boubyan"
    ]
   ],
   "primary_labels": [
    "bankboubyan",
    "boubyan"
   ],
   "priority": "high",
   "short_name": "Boubyan"
  },
  {
   "alias_labels": [
    "warba"
   ],
   "aliases": [],
   "arabic_keywords": [
    "وربة"
   ],
   "arabic_normalized": [
    "وربه"
   ],
   "domains": [
    "warbabank.com"
   ],
   "industry": "banking",
   "keywords": [
    "warba",
    "warba bank"
   ],
   "name": "Warba Bank",
   "phrases": [
    [
     "warba",
     "bank"
    ]
   ],
   "primary_labels": [
    "warbabank"
   ],
   "priority": "high",
   "short_name": "Warba"
  },
  {
   "alias_labels": [],
   "aliases": [],
   "arabic_keywords": [
    "الأهلي"
   ],
   "arabic_normalized": [
    "الاهلي"
   ],
   "domains": [
    "eahli.com"
   ],
   "industry": "banking",
   "keywords": [
    "abk",
    "al ahli bank",
    "eahli"
   ],
   "name": "Al Ahli Bank (ABK)",
   "phrases": [
    [
     "al",
     "ahli",
     "bank"
    ]
   ],
   "primary_labels": [
    "eahli"
   ],
   "priority": "high",
   "short_name": "ABK"
  },
  {
   "alias_labels": [],
   "aliases": [],
   "arabic_keywords": [],
   "arabic_normalized": [],
   "domains": [
    "kib.com"
   ],
   "industry": "banking",
   "keywords": [
    "kib",
    "global international bank"
   ],
   "name": "Global International Bank (KIB)",
   "phrases": [
    [
     "global",
     "international",
     "bank"
    ]
   ],
   "primary_labels": [
    "kib"
   ],
   "priority": "high",
   "short_name": "KIB"
  },
  {
   "alias_labels": [],
   "aliases": [],
   "arabic_keywords": [
    "الأهلي المتحد"
   ],
   "arabic_normalized": [
    "الاهلي المتحد"
   ],
   "domains": [
    "ahliunited.com"
   ],
   "industry": "banking",
   "keywords": [
    "ahliunited",
    "ahli united bank",
    "ahli united"
   ],
   "name": "Ahli United Bank",
   "phrases": [
    [
     "ahli",
     "united",
     "bank"
    ],
    [
     "ahli",
     "united"
    ]
   ],
   "primary_labels": [
    "ahliunited"
   ],
   "priority": "high",
   "short_name": "AUB"
  },
  {
   "alias_labels": [
    "knet",
    "knetonline",
    "knetpay",
    "knetpayment"
   ],
   "aliases": [
    "knetpay",
    "knetpayment",
    "knetonline"
   ],
   "arabic_keywords": [],
   "arabic_normalized": [],
   "domains": [
    "kpay.com"
   ],
   "industry": "payments",
   "keywords": [
    "knet",
    "kpay",
    "knet payment"
   ],
   "name": "KNET Electronic Payments",
   "phrases": [
    [
     "knet",
     "payment"
    ]
   ],
   "primary_labels": [
    "kpay"
   ],
   "priority": "critical",
   "short_name": "KNET"
  },
  {
   "alias_labels": [
    "zaincash"
   ],
   "aliases": [],
   "arabic_keywords": [
    "زين"
   ],
   "arabic_normalized": [
    "زين"
   ],
   "domains": [
    "zain.com"
   ],
   "industry": "telecom",
   "keywords": [
    "zain",
    "zain telecom",
    "zaincash"
   ],
   "name": "Zain Telecom",
   "phrases": [
    [
     "zain",
     "telecom"
    ]
   ],
   "primary_labels": [
    "zain"
   ],
   "priority": "high",
   "short_name": "Zain"
  },
  {
   "alias_labels": [],
   "aliases": [],
   "arabic_keywords": [
    "أوريدو"
   ],
   "arabic_normalized": [
    "اوريدو"
   ],
   "domains": [
    "ooredoo.com"
   ],
   "industry": "telecom",
   "keywords": [
    "ooredoo",
    "ooredoo telecom"
   ],
   "name": "Ooredoo Telecom",
   "phrases": [
    [
     "ooredoo",
     "telecom"
    ]
   ],
   "primary_labels": [
    "ooredoo"
   ],
   "priority": "high",
   "short_name": "Ooredoo"
  },
  {
   "alias_labels": [
    "stconline"
   ],
   "aliases": [
    "stconline"
   ],
   "arabic_keywords": [
    "اس تي سي"
   ],
   "arabic_normalized": [
    "اس تي سي"
   ],
   "domains": [
    "stc.com"
   ],
   "industry": "telecom",
   "keywords": [
    "stc telecom",
    "stc"
   ],
   "name": "stc Telecom",
   "phrases": [
    [
     "stc",
     "telecom"
    ]
   ],
   "primary_labels": [
    "stc"
   ],
   "priority": "high",
   "short_name": "stc"
  },
  {
   "alias_labels": [
    "egov",
    "sahel",
    "sahelapp"
   ],
   "aliases": [
    "sahel",
    "sahelapp"
   ],
   "arabic_keywords": [
    "سهل"
   ],
   "arabic_normalized": [
    "سهل"
   ],
   "domains": [
    "e-gov.org"
   ],
   "industry": "government",
   "keywords": [
    "egov",
    "sahel",
    "sahel portal"
   ],
   "name": "Centric eGovernment (Sahel)",
   "phrases": [
    [
     "sahel",
     "portal"
    ]
   ],
   "primary_labels": [
    "e-gov"
   ],
   "priority": "critical",
   "short_name": "eGov"
  },
  {
   "alias_labels": [
    "moigov"
   ],
   "aliases": [
    "moigov"
   ],
   "arabic_keywords": [
    "الداخلية"
   ],
   "arabic_normalized": [
    "الداخليه"
   ],
   "domains": [
    "moi-gov.org"
   ],
   "industry": "government",
   "keywords": [
    "moi",
    "ministry of interior"
   ],
   "name": "Ministry of Interior (MOI)",
   "phrases": [
    [
     "ministry",
     "of",
     "interior"
    ]
   ],
   "primary_labels": [
    "moi-gov"
   ],
   "priority": "critical",
   "short_name": "MOI"
  },
  {
   "alias_labels": [
    "civilid",
    "hawiyati",
    "paci"
   ],
   "aliases": [
    "civilid"
   ],
   "arabic_keywords": [
    "الهيئة العامة للمعلومات",
    "البطاقة المدنية",
    "هويتي"
   ],
   "arabic_normalized": [
    "الهييه العامه للمعلومات",
    "البطاقه المدنيه",
    "هويتي"
   ],
   "domains": [
    "paci-gov.org"
   ],
   "industry": "government",
   "keywords": [
    "paci",
    "civil information",
    "civil id",
    "hawiyati"
   ],
   "name": "Civil Identity Authority (PACI)",
   "phrases": [
    [
     "civil",
     "information"
    ],
    [
     "civil",
     "id"
    ]
   ],
   "primary_labels": [
    "paci-gov"
   ],
   "priority": "critical",
   "short_name": "PACI"
  },
  {
   "alias_labels": [],
   "aliases": [],
   "arabic_keywords": [
    "الصحة"
   ],
   "arabic_normalized": [
    "الصحه"
   ],
   "domains": [
    "moh-gov.org"
   ],
   "industry": "government",
   "keywords": [
    "moh",
    "ministry of health"
   ],
   "name": "Ministry of Health (MOH)",
   "phrases": [
    [
     "ministry",
     "of",
     "health"
    ]
   ],
   "primary_labels": [
    "moh-gov"
   ],
   "priority": "high",
   "short_name": "MOH"
  },
  {
   "alias_labels": [],
   "aliases": [],
   "arabic_keywords": [
    "التربية"
   ],
   "arabic_normalized": [
    "التربيه"
   ],
   "domains": [
    "moe-edu.org"
   ],
   "industry": "government",
   "keywords": [
    "moe",
    "ministry of education"
   ],
   "name": "Ministry of Education (MOE)",
   "phrases": [
    [
     "ministry",
     "of",
     "education"
    ]
   ],
   "primary_labels": [
    "moe-edu"
   ],
   "priority": "medium",
   "short_name": "MOE"
  },
  {
   "alias_labels": [],
   "aliases": [],
   "arabic_keywords": [],
   "arabic_normalized": [],
   "domains": [
    "globalairways.com"
   ],
   "industry": "aviation",
   "keywords": [
    "globalairways",
    "global airways"
   ],
   "name": "Global Sky Airways",
   "phrases": [
    [
     "global",
     "airways"
    ]
   ],
   "primary_labels": [
    "globalairways"
   ],
   "priority": "high",
   "short_name": "Global Airways"
  },
  {
   "alias_labels": [],
   "aliases": [],
   "arabic_keywords": [
    "طيران الجزيرة"
   ],
   "arabic_normalized": [
    "طيران الجزيره"
   ],
   "domains": [
    "jazeeraairways.com"
   ],
   "industry": "aviation",
   "keywords": [
    "jazeeraairways",
    "jazeera airways"
   ],
   "name": "Jazeera Airways",
   "phrases": [
    [
     "jazeera",
     "airways"
    ]
   ],
   "primary_labels": [
    "jazeeraairways"
   ],
   "priority": "medium",
   "short_name": "Jazeera"
  },
  {
   "alias_labels": [],
   "aliases": [],
   "arabic_keywords": [],
   "arabic_normalized": [],
   "domains": [
    "knpc.com"
   ],
   "industry": "energy",
   "keywords": [
    "knpc",
    "national petroleum"
   ],
   "name": "National Petroleum Company (KNPC)",
   "phrases": [
    [
     "national",
     "petroleum"
    ]
   ],
   "primary_labels": [
    "knpc"
   ],
   "priority": "medium",
   "short_name": "KNPC"
  },
  {
   "alias_labels": [],
   "aliases": [],
   "arabic_keywords": [],
   "arabic_normalized": [],
   "domains": [
    "kpc-corp.com"
   ],
   "industry": "energy",
   "keywords": [
    "kpc",
    "petroleum corporation"
   ],
   "name": "Petroleum Corporation (KPC)",
   "phrases": [
    [
     "petroleum",
     "corporation"
    ]
   ],
   "primary_labels": [
    "kpc-corp"
   ],
   "priority": "medium",
   "short_name": "KPC"
  },
  {
   "alias_labels": [
    "boursa"
   ],
   "aliases": [],
   "arabic_keywords": [],
   "arabic_normalized": [],
   "domains": [
    "boursa-exchange.com"
   ],
   "industry": "finance",
   "keywords": [
    "boursa",
    "securities exchange"
   ],
   "name": "Securities Exchange (Boursa)",
   "phrases": [
    [
     "securities",
     "exchange"
    ]
   ],
   "primary_labels": [
    "boursa-exchange"
   ],
   "priority": "medium",
   "short_name": "Boursa"
  },
  {
   "alias_labels": [],
   "aliases": [],
   "arabic_keywords": [
    "طلبات"
   ],
   "arabic_normalized": [
    "طلبات"
   ],
   "domains": [
    "talabat.com"
   ],
   "industry": "ecommerce",
   "keywords": [
    "talabat"
   ],
   "name": "Talabat",
   "phrases": [],
   "primary_labels": [
    "talabat"
   ],
   "priority": "medium",
   "short_name": "Talabat"
  }
 ],
 "certstream_keywords": [
  "brandsentra",
  "novapay",
  "n0vapay",
  "kestrel",
  "kestrelmart",
  "halcyon",
  "halcyonhealth",
  "meridianbank",
  "apexcloud",
  "luminatelecom",
  "vertexsec",
  "horizonlogistics",
  "secure-login",
  "auth-portal",
  "verify-identity",
  "account-update",
  "payment-gateway",
  "support-desk",
  "onlinebanking",
  "security-alert",
  "signin"
 ],
 "combo_keywords": [
  "5g",
  "account",
  "accounts",
  "activate",
  "activation",
  "admin",
  "alert",
  "alerts",
  "app",
  "apps",
  "auth",
  "balance",
  "bank",
  "banking",
  "bill",
  "billing",
  "bills",
  "bonus",
  "book",
  "booking",
  "card",
  "cards",
  "career",
  "careers",
  "cashback",
  "center",
  "centre",
  "checkin",
  "click",
  "client",
  "cloud",
  "com",
  "confirm",
  "credit",
  "crypto",
  "customer",
  "customers",
  "data",
  "delivery",
  "deposit",
  "digital",
  "direct",
  "ebank",
  "ebanking",
  "email",
  "esim",
  "express",
  "fiber",
  "fine",
  "fines",
  "flight",
  "flights",
  "get",
  "gift",
  "global",
  "go",
  "gov",
  "group",
  "help",
  "helpdesk",
  "hr",
  "id",
  "info",
  "international",
  "internet",
  "investment",
  "invoice",
  "job",
  "jobs",
  "kyc",
  "link",
  "live",
  "loan",
  "loans",
  "login",
  "logon",
  "loyalty",
  "mail",
  "me",
  "miles",
  "mobile",
  "my",
  "net",
  "netbanking",
  "new",
  "notice",
  "now",
  "offer",
  "offers",
  "official",
  "online",
  "order",
  "orders",
  "org",
  "otp",
  "parcel",
  "pay",
  "payment",
  "payments",
  "plus",
  "points",
  "portal",
  "prize",
  "pro",
  "promo",
  "recharge",
  "refund",
  "renew",
  "renewal",
  "reservation",
  "reset",
  "reward",
  "rewards",
  "salary",
  "savings",
  "secure",
  "security",
  "service",
  "services",
  "shop",
  "signin",
  "sim",
  "smart",
  "statement",
  "stocks",
  "store",
  "support",
  "tax",
  "team",
  "the",
  "ticket",
  "tickets",
  "topup",
  "track",
  "tracking",
  "trading",
  "traffic",
  "transfer",
  "update",
  "user",
  "users",
  "validate",
  "validation",
  "verification",
  "verify",
  "visa",
  "wallet",
  "web",
  "wifi",
  "www"
 ],
 "confusables": {
  "ð": "d",
  "ø": "o",
  "þ": "p",
  "đ": "d",
  "ı": "i",
  "ł": "l",
  "ƒ": "f",
  "ɑ": "a",
  "ɡ": "g",
  "ɢ": "g",
  "ɩ": "i",
  "ɪ": "i",
  "ɴ": "n",
  "ʀ": "r",
  "ʏ": "y",
  "ʙ": "b",
  "ʟ": "l",
  "α": "a",
  "β": "b",
  "γ": "y",
  "ε": "e",
  "η": "n",
  "ι": "i",
  "κ": "k",
  "μ": "u",
  "ν": "v",
  "ο": "o",
  "ρ": "p",
  "τ": "t",
  "υ": "u",
  "χ": "x",
  "ω": "w",
  "ϖ": "w",
  "ϱ": "p",
  "ϲ": "c",
  "ϳ": "j",
  "а": "a",
  "в": "b",
  "г": "r",
  "е": "e",
  "з": "z",
  "к": "k",
  "м": "m",
  "н": "h",
  "о": "o",
  "п": "n",
  "р": "p",
  "с": "c",
  "т": "t",
  "у": "y",
  "х": "x",
  "ц": "u",
  "ъ": "b",
  "ь": "b",
  "ё": "e",
  "є": "e",
  "ѕ": "s",
  "і": "i",
  "ї": "i",
  "ј": "j",
  "ѵ": "v",
  "ғ": "f",
  "ү": "y",
  "һ": "h",
  "ӏ": "l",
  "ө": "o",
  "ԁ": "d",
  "ԛ": "q",
  "ԝ": "w",
  "ա": "a",
  "զ": "q",
  "ժ": "d",
  "հ": "h",
  "ո": "n",
  "ս": "u",
  "ց": "g",
  "ք": "p",
  "օ": "o",
  "ᴀ": "a",
  "ᴄ": "c",
  "ᴇ": "e",
  "ᴊ": "j",
  "ᴋ": "k",
  "ᴍ": "m",
  "ᴏ": "o",
  "ᴘ": "p",
  "ᴛ": "t",
  "ᴜ": "u",
  "ᴠ": "v",
  "ᴡ": "w",
  "ᴢ": "z",
  "ℓ": "l",
  "ℯ": "e",
  "ℴ": "o",
  "ⅰ": "i",
  "ⅴ": "v",
  "ⅹ": "x",
  "ⅼ": "l",
  "ⅽ": "c",
  "ⅾ": "d",
  "ⅿ": "m",
  "ꜱ": "s",
  "ꝺ": "d",
  "ꞵ": "b",
  "ꬲ": "e",
  "ｅ": "e"
 },
 "context_tokens": [
  "account",
  "auth",
  "bank",
  "cloud",
  "corp",
  "gov",
  "login",
  "online",
  "pay",
  "portal",
  "secure",
  "verify"
 ],
 "embedded_tld_tokens": [
  "co",
  "com",
  "gov",
  "net",
  "org"
 ],
 "free_ca_markers": [
  "let's encrypt",
  "letsencrypt",
  "zerossl",
  "buypass",
  "google trust services"
 ],
 "generation_combos": [
  "login",
  "secure",
  "verify",
  "online",
  "account",
  "update",
  "support",
  "portal",
  "bank",
  "pay",
  "app",
  "mobile",
  "cloud",
  "corp",
  "global",
  "otp",
  "card",
  "service",
  "help",
  "official"
 ],
 "global_brands": [
  "adobe",
  "amazon",
  "americanexpress",
  "apple",
  "aramex",
  "binance",
  "chase",
  "citibank",
  "coinbase",
  "dhl",
  "docusign",
  "dropbox",
  "facebook",
  "fedex",
  "gmail",
  "google",
  "hsbc",
  "icloud",
  "instagram",
  "linkedin",
  "mastercard",
  "metamask",
  "microsoft",
  "netflix",
  "office365",
  "onedrive",
  "outlook",
  "paypal",
  "sharepoint",
  "spotify",
  "steam",
  "telegram",
  "usps",
  "wellsfargo",
  "whatsapp"
 ],
 "high_risk_tlds": [
  "accountant",
  "bar",
  "bid",
  "bond",
  "buzz",
  "cam",
  "cf",
  "cfd",
  "country",
  "cricket",
  "cyou",
  "date",
  "download",
  "faith",
  "ga",
  "gdn",
  "gq",
  "icu",
  "kim",
  "loan",
  "lol",
  "men",
  "ml",
  "mom",
  "monster",
  "mov",
  "party",
  "quest",
  "racing",
  "rest",
  "review",
  "sbs",
  "science",
  "stream",
  "surf",
  "tk",
  "trade",
  "wang",
  "win",
  "zip"
 ],
 "homoglyphs": {
  "a": [
   "à",
   "á",
   "â",
   "ä",
   "α",
   "а",
   "ạ"
  ],
  "b": [
   "d",
   "ḅ",
   "ʙ",
   "Ь"
  ],
  "c": [
   "ç",
   "ć",
   "с",
   "ϲ"
  ],
  "d": [
   "b",
   "ḍ",
   "ɗ",
   "ԁ"
  ],
  "e": [
   "è",
   "é",
   "ê",
   "ë",
   "е",
   "ẹ"
  ],
  "g": [
   "q",
   "ɡ",
   "ġ"
  ],
  "h": [
   "ḥ",
   "ħ",
   "һ"
  ],
  "i": [
   "1",
   "l",
   "í",
   "ì",
   "ï",
   "і",
   "ı"
  ],
  "k": [
   "ḳ",
   "ĸ",
   "к"
  ],
  "l": [
   "1",
   "i",
   "ł",
   "ӏ"
  ],
  "m": [
   "rn",
   "ṃ",
   "м"
  ],
  "n": [
   "ñ",
   "ṇ",
   "п"
  ],
  "o": [
   "0",
   "ó",
   "ò",
   "ö",
   "ø",
   "о",
   "ο"
  ],
  "p": [
   "ṗ",
   "р",
   "ρ"
  ],
  "q": [
   "g",
   "ԛ"
  ],
  "r": [
   "ṛ",
   "ŗ",
   "г"
  ],
  "s": [
   "5",
   "ṣ",
   "ś",
   "ş",
   "ѕ"
  ],
  "t": [
   "ṭ",
   "ţ",
   "т"
  ],
  "u": [
   "ú",
   "ù",
   "ü",
   "ū",
   "ц",
   "υ"
  ],
  "v": [
   "ṿ",
   "ν",
   "ѵ"
  ],
  "w": [
   "vv",
   "ẁ",
   "ẃ",
   "ԝ"
  ],
  "x": [
   "ẋ",
   "х",
   "χ"
  ],
  "y": [
   "ý",
   "ÿ",
   "ŷ",
   "у"
  ],
  "z": [
   "ẓ",
   "ź",
   "ż",
   "з"
  ]
 },
 "keyboard_adjacent": {
  "0": "9op",
  "1": "2q",
  "2": "13qw",
  "3": "24we",
  "4": "35er",
  "5": "46rt",
  "6": "57ty",
  "7": "68yu",
  "8": "79ui",
  "9": "80io",
  "a": "qwsz",
  "b": "vghn",
  "c": "xdfv",
  "d": "ersfxc",
  "e": "wrds",
  "f": "rtdgcv",
  "g": "tyfhvb",
  "h": "yugjbn",
  "i": "uojk",
  "j": "uihknm",
  "k": "oijlm",
  "l": "pk",
  "m": "njk",
  "n": "bhjm",
  "o": "iplk",
  "p": "ol",
  "q": "wa",
  "r": "etdf",
  "s": "weadxz",
  "t": "ryfg",
  "u": "yijh",
  "v": "cfgb",
  "w": "qeas",
  "x": "zsdc",
  "y": "tugh",
  "z": "asx"
 },
 "leet_generation": {
  "a": [
   "4"
  ],
  "b": [
   "8"
  ],
  "e": [
   "3"
  ],
  "g": [
   "9"
  ],
  "i": [
   "1"
  ],
  "l": [
   "1"
  ],
  "o": [
   "0"
  ],
  "s": [
   "5"
  ],
  "t": [
   "7"
  ]
 },
 "leet_map": {
  "!": "i",
  "$": "s",
  "0": "o",
  "1": "l",
  "3": "e",
  "4": "a",
  "5": "s",
  "7": "t",
  "8": "b",
  "9": "g",
  "@": "a",
  "|": "l"
 },
 "medium_risk_tlds": [
  "app",
  "asia",
  "bank",
  "best",
  "biz",
  "cash",
  "cc",
  "center",
  "click",
  "cloud",
  "club",
  "cn",
  "co",
  "credit",
  "dev",
  "digital",
  "email",
  "finance",
  "fit",
  "fun",
  "help",
  "info",
  "life",
  "link",
  "live",
  "me",
  "money",
  "one",
  "online",
  "page",
  "pics",
  "pw",
  "ru",
  "run",
  "services",
  "shop",
  "site",
  "solutions",
  "space",
  "store",
  "su",
  "support",
  "tech",
  "today",
  "top",
  "vip",
  "website",
  "work",
  "world",
  "ws",
  "xyz"
 ],
 "official_suffixes": [
  "edu",
  "gov",
  "int",
  "mil"
 ],
 "official_tokens": [
  "e-gov",
  "egov",
  "gov",
  "government",
  "govt",
  "ministry"
 ],
 "phishing_keywords": [
  "account",
  "accounts",
  "activate",
  "activation",
  "alert",
  "auth",
  "authenticate",
  "authentication",
  "bank",
  "banking",
  "billing",
  "bonus",
  "cashback",
  "confirm",
  "confirmation",
  "credential",
  "credentials",
  "customs",
  "delivery",
  "docusign",
  "ebanking",
  "fine",
  "fines",
  "gift",
  "giftcard",
  "helpdesk",
  "invoice",
  "kyc",
  "log-in",
  "login",
  "logon",
  "mailbox",
  "microsoft365",
  "netbanking",
  "notice",
  "office-365",
  "office365",
  "onedrive",
  "onlinebanking",
  "otp",
  "parcel",
  "passcode",
  "password",
  "payment",
  "payments",
  "pin",
  "prize",
  "promo",
  "recover",
  "recovery",
  "refund",
  "renew",
  "renewal",
  "restrict",
  "restricted",
  "reward",
  "rewards",
  "secure",
  "security",
  "sharepoint",
  "shipment",
  "sign-in",
  "signin",
  "social-security",
  "ssn",
  "statement",
  "support",
  "suspend",
  "suspended",
  "tax-refund",
  "traffic",
  "unlock",
  "update",
  "updates",
  "urgent",
  "validate",
  "validation",
  "verification",
  "verified",
  "verify",
  "violation",
  "wallet",
  "webmail",
  "winner"
 ],
 "protected_brands": [
  "novapay.com",
  "kestrelmart.com",
  "halcyonhealth.org",
  "meridianbank.com",
  "apexcloud.io",
  "luminatelecom.com",
  "vertexsecurity.com",
  "horizonlogistics.com"
 ],
 "squat_tlds": [
  "com",
  "net",
  "org",
  "co",
  "info",
  "biz",
  "me",
  "io",
  "app",
  "xyz",
  "top",
  "online",
  "site",
  "icu",
  "club",
  "live",
  "shop",
  "cc",
  "link",
  "click"
 ],
 "suffixes": {
  "free_hosting": [
   "000webhostapp.com",
   "appspot.com",
   "azurestaticapps.net",
   "azurewebsites.net",
   "bio.link",
   "blob.core.windows.net",
   "blogspot.com",
   "bubbleapps.io",
   "canva.site",
   "carrd.co",
   "cloudfront.net",
   "ddns.net",
   "duckdns.org",
   "dweb.link",
   "firebaseapp.com",
   "fly.dev",
   "forms.gle",
   "framer.app",
   "framer.website",
   "github.io",
   "gitlab.io",
   "glideapp.io",
   "glitch.me",
   "godaddysites.com",
   "googleusercontent.com",
   "herokuapp.com",
   "hopto.org",
   "ipfs.dweb.link",
   "ipfs.io",
   "jimdosite.com",
   "linktr.ee",
   "loca.lt",
   "mailchimpsites.com",
   "my.canva.site",
   "my.sharepoint.com",
   "myftp.org",
   "mystrikingly.com",
   "netlify.app",
   "ngrok-free.app",
   "ngrok.app",
   "ngrok.io",
   "no-ip.org",
   "notion.site",
   "onrender.com",
   "pages.dev",
   "r2.dev",
   "railway.app",
   "repl.co",
   "replit.app",
   "s3-website.amazonaws.com",
   "s3.amazonaws.com",
   "serveo.net",
   "sharepoint.com",
   "sites.google.com",
   "softr.app",
   "square.site",
   "surge.sh",
   "sytes.net",
   "t.me",
   "telegra.ph",
   "trycloudflare.com",
   "typeform.com",
   "vercel.app",
   "web-app.com",
   "web.app",
   "web.core.windows.net",
   "webador.com",
   "webflow.io",
   "webnode.page",
   "weebly.com",
   "wixsite.com",
   "wixstudio.io",
   "wordpress.com",
   "workers.dev",
   "yolasite.com",
   "z13.web.core.windows.net",
   "zapto.org"
  ],
  "gcc_mena": [
   "ac.ae",
   "ac.ir",
   "ac.ma",
   "bel.tr",
   "co.ae",
   "co.ir",
   "co.ma",
   "com.bh",
   "com.dz",
   "com.eg",
   "com.iq",
   "com.jo",
   "com.lb",
   "com.om",
   "com.pk",
   "com.qa",
   "com.sa",
   "com.tn",
   "com.tr",
   "edu.bh",
   "edu.dz",
   "edu.eg",
   "edu.iq",
   "edu.jo",
   "edu.lb",
   "edu.om",
   "edu.pk",
   "edu.qa",
   "edu.sa",
   "edu.tr",
   "eun.eg",
   "gov.ae",
   "gov.bh",
   "gov.dz",
   "gov.eg",
   "gov.iq",
   "gov.ir",
   "gov.jo",
   "gov.lb",
   "gov.ma",
   "gov.om",
   "gov.pk",
   "gov.qa",
   "gov.sa",
   "gov.tn",
   "gov.tr",
   "med.om",
   "med.sa",
   "mil.ae",
   "mil.qa",
   "net.ae",
   "net.bh",
   "net.eg",
   "net.iq",
   "net.jo",
   "net.lb",
   "net.om",
   "net.pk",
   "net.qa",
   "net.sa",
   "net.tr",
   "org.ae",
   "org.bh",
   "org.eg",
   "org.iq",
   "org.ir",
   "org.jo",
   "org.lb",
   "org.ma",
   "org.om",
   "org.pk",
   "org.qa",
   "org.sa",
   "org.tn",
   "org.tr",
   "pub.sa",
   "sch.ae",
   "sch.sa"
  ],
  "global": [
   "ac.id",
   "ac.il",
   "ac.in",
   "ac.jp",
   "ac.kr",
   "ac.nz",
   "ac.th",
   "ac.uk",
   "ac.za",
   "co.id",
   "co.il",
   "co.in",
   "co.jp",
   "co.ke",
   "co.kr",
   "co.nz",
   "co.th",
   "co.tz",
   "co.ug",
   "co.uk",
   "co.za",
   "com.ar",
   "com.au",
   "com.bd",
   "com.bo",
   "com.br",
   "com.cn",
   "com.co",
   "com.do",
   "com.ec",
   "com.et",
   "com.gh",
   "com.gt",
   "com.hk",
   "com.ke",
   "com.kz",
   "com.lk",
   "com.mx",
   "com.my",
   "com.ng",
   "com.np",
   "com.pa",
   "com.pe",
   "com.ph",
   "com.pl",
   "com.pr",
   "com.py",
   "com.ru",
   "com.sg",
   "com.sv",
   "com.tw",
   "com.ua",
   "com.uy",
   "com.ve",
   "com.vn",
   "edu.ar",
   "edu.au",
   "edu.bd",
   "edu.br",
   "edu.cn",
   "edu.co",
   "edu.gh",
   "edu.hk",
   "edu.mx",
   "edu.my",
   "edu.ng",
   "edu.ph",
   "edu.pl",
   "edu.sg",
   "edu.tw",
   "edu.vn",
   "firm.in",
   "go.id",
   "go.jp",
   "go.ke",
   "go.kr",
   "go.th",
   "go.tz",
   "go.ug",
   "gob.ar",
   "gob.bo",
   "gob.do",
   "gob.ec",
   "gob.gt",
   "gob.mx",
   "gob.pa",
   "gob.pe",
   "gob.sv",
   "gob.ve",
   "gov.au",
   "gov.bd",
   "gov.br",
   "gov.cn",
   "gov.co",
   "gov.et",
   "gov.gh",
   "gov.hk",
   "gov.il",
   "gov.in",
   "gov.kz",
   "gov.lk",
   "gov.my",
   "gov.ng",
   "gov.np",
   "gov.ph",
   "gov.pl",
   "gov.pr",
   "gov.py",
   "gov.sg",
   "gov.tw",
   "gov.ua",
   "gov.uk",
   "gov.vn",
   "gov.za",
   "govt.nz",
   "gub.uy",
   "ltd.uk",
   "me.uk",
   "ne.jp",
   "ne.kr",
   "net.au",
   "net.br",
   "net.cn",
   "net.hk",
   "net.il",
   "net.in",
   "net.my",
   "net.nz",
   "net.pl",
   "net.ru",
   "net.sg",
   "net.tw",
   "net.ua",
   "net.uk",
   "net.vn",
   "nhs.uk",
   "or.id",
   "or.jp",
   "or.ke",
   "or.kr",
   "or.th",
   "org.ar",
   "org.au",
   "org.bd",
   "org.br",
   "org.cn",
   "org.hk",
   "org.il",
   "org.in",
   "org.mx",
   "org.my",
   "org.ng",
   "org.nz",
   "org.ph",
   "org.pl",
   "org.ru",
   "org.sg",
   "org.tw",
   "org.ua",
   "org.uk",
   "org.vn",
   "org.za",
   "plc.uk",
   "sch.uk",
   "web.id"
  ],
  "regional": [
   "com.kw",
   "edu.kw",
   "emb.kw",
   "gov.kw",
   "ind.kw",
   "mil.kw",
   "net.kw",
   "org.kw"
  ]
 },
 "version": "2.5.0",
 "visual_sequences": [
  [
   "rn",
   "m"
  ],
  [
   "vv",
   "w"
  ],
  [
   "cl",
   "d"
  ],
  [
   "nn",
   "m"
  ]
 ]
};})(typeof window!=='undefined'?window:globalThis);
